services:
  - type: web
    name: skillswap-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && bash build.sh
    startCommand: cd backend && gunicorn skillswap.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
